# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.models import model_from_json
from sklearn.preprocessing import normalize
import matplotlib.pyplot as plt
import numpy as np

if hasattr(QtCore.Qt, 'AA_EnableHighDpiScaling'):
    QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)

if hasattr(QtCore.Qt, 'AA_UseHighDpiPixmaps'):
    QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1293, 610)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        Form.setStyleSheet("background-color: rgb(100, 100, 100);")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(240, 10, 791, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 170, 127);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 51, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 170, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(150, 52, 471, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 170, 255);")
        self.label_2.setObjectName("label_2")
        self.pushButton_show_result = QtWidgets.QPushButton(Form)
        self.pushButton_show_result.setGeometry(QtCore.QRect(250, 498, 881, 41))
        self.pushButton_show_result.clicked.connect(self.process)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_show_result.setFont(font)
        self.pushButton_show_result.setStyleSheet("color: rgb(255, 170, 255);")
        self.pushButton_show_result.setObjectName("pushButton_show_result")
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setGeometry(QtCore.QRect(130, 548, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(85, 170, 255);")
        self.label_30.setObjectName("label_30")
        self.label_show_bei = QtWidgets.QLabel(Form)
        self.label_show_bei.setGeometry(QtCore.QRect(251, 549, 881, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_show_bei.setFont(font)
        self.label_show_bei.setStyleSheet("color: rgb(0, 170, 0);")
        self.label_show_bei.setText("")
        self.label_show_bei.setAlignment(QtCore.Qt.AlignCenter)
        self.label_show_bei.setObjectName("label_show_bei")
        self.label_32 = QtWidgets.QLabel(Form)
        self.label_32.setGeometry(QtCore.QRect(1170, 549, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: rgb(85, 170, 255);")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(Form)
        self.label_33.setGeometry(QtCore.QRect(31, 119, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(255, 170, 255);")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(Form)
        self.label_34.setGeometry(QtCore.QRect(150, 120, 481, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(255, 170, 255);")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(Form)
        self.label_35.setGeometry(QtCore.QRect(510, 149, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(255, 170, 255);")
        self.label_35.setObjectName("label_35")
        self.label_48 = QtWidgets.QLabel(Form)
        self.label_48.setGeometry(QtCore.QRect(490, 219, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(Form)
        self.label_49.setGeometry(QtCore.QRect(254, 204, 651, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(Form)
        self.label_50.setGeometry(QtCore.QRect(320, 187, 481, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(Form)
        self.label_51.setGeometry(QtCore.QRect(254, 275, 661, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(Form)
        self.label_52.setGeometry(QtCore.QRect(440, 259, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(Form)
        self.label_53.setGeometry(QtCore.QRect(470, 289, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(Form)
        self.label_54.setGeometry(QtCore.QRect(430, 319, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(Form)
        self.label_55.setGeometry(QtCore.QRect(470, 359, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(Form)
        self.label_56.setGeometry(QtCore.QRect(254, 341, 651, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(Form)
        self.label_57.setGeometry(QtCore.QRect(254, 417, 651, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(Form)
        self.label_58.setGeometry(QtCore.QRect(490, 429, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(Form)
        self.label_59.setGeometry(QtCore.QRect(400, 400, 331, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_59.setObjectName("label_59")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(33, 192, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(33, 409, 221, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_21.setObjectName("label_21")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(33, 269, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(33, 339, 181, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_20.setObjectName("label_20")
        self.textEdit_logic = QtWidgets.QTextEdit(Form)
        self.textEdit_logic.setGeometry(QtCore.QRect(925, 199, 201, 31))
        self.textEdit_logic.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_logic.setObjectName("textEdit_logic")
        self.textEdit_hard_constraints = QtWidgets.QTextEdit(Form)
        self.textEdit_hard_constraints.setGeometry(QtCore.QRect(925, 409, 201, 31))
        self.textEdit_hard_constraints.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_hard_constraints.setObjectName("textEdit_hard_constraints")
        self.textEdit_lags = QtWidgets.QTextEdit(Form)
        self.textEdit_lags.setGeometry(QtCore.QRect(925, 269, 201, 31))
        self.textEdit_lags.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_lags.setObjectName("textEdit_lags")
        self.textEdit_relationships = QtWidgets.QTextEdit(Form)
        self.textEdit_relationships.setGeometry(QtCore.QRect(925, 339, 201, 31))
        self.textEdit_relationships.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_relationships.setObjectName("textEdit_relationships")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(1164, 199, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_26.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setGeometry(QtCore.QRect(1164, 409, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_29.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(1164, 269, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_27.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setGeometry(QtCore.QRect(1164, 339, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_28.setStyleSheet("color: rgb(255, 134, 123);")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_37 = QtWidgets.QLabel(Form)
        self.label_37.setGeometry(QtCore.QRect(950, 149, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: rgb(255, 170, 255);")
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.label_36 = QtWidgets.QLabel(Form)
        self.label_36.setGeometry(QtCore.QRect(1140, 149, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: rgb(255, 170, 255);")
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.label_18.raise_()
        self.label_21.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.textEdit_logic.raise_()
        self.textEdit_hard_constraints.raise_()
        self.textEdit_lags.raise_()
        self.textEdit_relationships.raise_()
        self.label_26.raise_()
        self.label_29.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.label_37.raise_()
        self.label_36.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.label_5.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton_show_result.raise_()
        self.label_30.raise_()
        self.label_show_bei.raise_()
        self.label_32.raise_()
        self.label_48.raise_()
        self.label_49.raise_()
        self.label_50.raise_()
        self.label_51.raise_()
        self.label_52.raise_()
        self.label_53.raise_()
        self.label_54.raise_()
        self.label_55.raise_()
        self.label_56.raise_()
        self.label_57.raise_()
        self.label_58.raise_()
        self.label_59.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "QEBS"))
        self.label_5.setText(_translate("Form", "Quantitative Evaluation for baseline schedule"))
        self.label.setText(_translate("Form", "Phase 1 :"))
        self.label_2.setText(_translate("Form", "Check Metrics with Exact Threshold"))
        self.pushButton_show_result.setText(_translate("Form", "Show Result"))
        self.label_30.setText(_translate("Form", "BEI ="))
        self.label_32.setText(_translate("Form", "≥ 1"))
        self.label_33.setText(_translate("Form", "Phase 2 :"))
        self.label_34.setText(_translate("Form", "Metrics with Wide Range Threshold"))
        self.label_35.setText(_translate("Form", "Calculate"))
        self.label_48.setText(_translate("Form", "Total of Activities"))
        self.label_49.setText(_translate("Form", "=  ---------------------------------------------------------------------------------  x 100"))
        self.label_50.setText(_translate("Form", "No of Activities without Predecessor and/or Successsor"))
        self.label_51.setText(_translate("Form", "=  ---------------------------------------------------------------------------------  x 100"))
        self.label_52.setText(_translate("Form", "No of Relationships with Lags"))
        self.label_53.setText(_translate("Form", "Total of Relationships"))
        self.label_54.setText(_translate("Form", "No of Finish to Start Relationships"))
        self.label_55.setText(_translate("Form", "Total of Relationships"))
        self.label_56.setText(_translate("Form", "=  ---------------------------------------------------------------------------------  x 100"))
        self.label_57.setText(_translate("Form", "=  ---------------------------------------------------------------------------------  x 100"))
        self.label_58.setText(_translate("Form", "Total of Activities"))
        self.label_59.setText(_translate("Form", "No of Activities with Hard Constraints"))
        self.label_18.setText(_translate("Form", "Logic"))
        self.label_21.setText(_translate("Form", "Hard Constraints"))
        self.label_19.setText(_translate("Form", "Lags"))
        self.label_20.setText(_translate("Form", "Relationships"))
        self.label_26.setText(_translate("Form", "≤ 5 %"))
        self.label_29.setText(_translate("Form", "≤ 5 %"))
        self.label_27.setText(_translate("Form", "≤ 5 %"))
        self.label_28.setText(_translate("Form", "≥ 90%"))
        self.label_37.setText(_translate("Form", "Input"))
        self.label_36.setText(_translate("Form", "Threshold"))

    def process(self):
        # load json and create model
        json_file = open('model.json', 'r')
        loaded_model_json = json_file.read()
        json_file.close()
        loaded_model = model_from_json(loaded_model_json)
        # load weights into new model
        loaded_model.load_weights("model.h5")

        self.logic = self.textEdit_logic.toPlainText()
        self.lags = self.textEdit_lags.toPlainText()
        self.relationship = self.textEdit_relationships.toPlainText()
        self.constraints = self.textEdit_hard_constraints.toPlainText()

        self.values = [float(self.logic), float(self.lags), float(self.relationship), float(self.constraints)]
        self.values = np.array(self.values).reshape(1, -1)
        self.values = normalize(self.values)
        res = loaded_model.predict(self.values)[0][0]

        self.label_show_bei.setText(str(res))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
